### ISSUE TITLE
Multiecho RESHAPE Error

### ISSUE THREAD

**Issue by umbertozanovello** [leoliuf/MRiLab#12]
I was trying to use the multiecho feature in some sequences (Standard SE and GRE).
However, I get the following error : "Recon process aborted. To RESHAPE the number of elements must not change.". I tried different "TEPerTR" values and different "ME_TEs" arrays but nothing changed.
I think that the incriminated reshape function is that in "DoCartRecon.m". Am I missing something?

Thank you very much!

Umberto

**Comment by leoliuf** [comment]
Please see the example of PSD_AFI for the pulse sequence diagram. The TEPerTR and ME_TEs are used to conveniently pass the values (i.e. TE values, VCtl.ME_TEs(1)) from the interface to MR sequence, you have to implement readout filter (i.e. ADC) in the sequence to create actual signal acquisition. Thanks.
