### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by drwillis** [leoliuf/MRiLab#14]
Tried this on linux distribution Ubuntu 16.04. Can't run the demo Gradient Echo sequence. It's looking for libcudart version 7.0. This distribution of linux uses libcudart 7.5. Any suggestions? Can I force CPU simulation somehow?

**Comment by leoliuf** [comment]
You might need to recompile the GPU engines to use cuda7.5. Also you can use CPU mode by selecting CPU engine from the drop-down menu of the main simulation GUI.
