### ISSUE TITLE
CV3 variable is not taken into account in PSD_FIESTA3D sequence

### ISSUE THREAD

**Issue by romainVala** [leoliuf/MRiLab#2]
Hello

First many thanks for this nice sofware, it is quite an amazing work. I do not know if it is the right place to ask. but in case :
I notice that if I change the CV3 value in the graphical interface click on update, and then scan the new value is not taken into account. 
I compare it to the case where I change the CV3 value in the .xml config file of the sequence, before loading it in the gui

Is there a quick fix, or can you tel me where to have a look ?

Many thanks

Romain

**Comment by leoliuf** [comment]
Any modification made to CVs requires to save by pressing 'Save' push-button prior to being effective.

**Comment by romainVala** [comment]
yes indeed,

thanks
