### ISSUE TITLE
DoScanAtCPU

### ISSUE THREAD

**Issue by FZihan** [leoliuf/MRiLab#21]
I have a problem after compiling MEX files,
I set Matlab2015a and Framewave 1.3 in my system environment path.
By following the MRiLab manual:
Build the INSTALL project, compiled MEX binaries will be copied to MRiLab/Lib/bin folder by default, 
A DoScanAtCPU.mexaw64 copied in the bin folder, which is 94 KB.
After pressing K-space in sequence design panel I got this message:
![ksp](https://user-images.githubusercontent.com/52111410/60400762-c2a81480-9b8d-11e9-8e23-2adedceafdfc.jpg)

![2](https://user-images.githubusercontent.com/52111410/60400870-40b8eb00-9b8f-11e9-9568-b89fecc5a431.jpg)

Could you please help me where is the problem?

**Comment by leoliuf** [comment]
You probably want to use some tools to detect which module is missing. You can use this one.
http://www.dependencywalker.com/

**Comment by elmirayazdani** [comment]
Dependencywalker found these modules: 
![12](https://user-images.githubusercontent.com/48117052/60418817-23206b80-9bf9-11e9-86d0-aac67b5d80af.jpg)
What should I do now?
Thank you for your time

**Comment by ElmiraYazdani** [comment]
I have the same problem 
Dependencywalker found these modules:
What should I do now?
Thank you for your time
![12](https://user-images.githubusercontent.com/48117052/60440888-0ac94480-9c2b-11e9-816c-31d1c3ad41c0.jpg)

**Comment by leoliuf** [comment]
@elmirayazdani You need to add the Framewave path containing the missing DLLs into the system environment. Check this thread for how to add DLL path in Windows https://stackoverflow.com/questions/694351/setting-library-path-for-win32-console-applications

But, you can also compile against static libraries *.lib so as to avoid loading .dll in runtime.

**Comment by ElmiraYazdani** [comment]
I have the dlls in my system path:
![dll](https://user-images.githubusercontent.com/52111410/60518288-73c9be80-9cf6-11e9-8b39-11ddc697d682.jpg)
Is there any problem with the FW_1.3_Win64?

**Comment by leoliuf** [comment]
@elmirayazdani You need to add the path into the 'PATH' system variable to allow Windows looking for the DLLs.

**Comment by FZihan** [comment]
Thank you Dr. Liu
I've used the dependencywalker, but there is no error, just 2 warning!
May I ask you to take a look at this picture:
![ds](https://user-images.githubusercontent.com/52111410/60568605-8db0e300-9d82-11e9-8b95-a41f407997ab.jpg)

**Comment by ElmiraYazdani** [comment]
I added Framewave's dlls to my "PATH" of the system and now:
![1](https://user-images.githubusercontent.com/48117052/60575571-09b22780-9d91-11e9-8458-d2da38ce9078.jpg)
Where is the problem?
Thank you for all your help

**Comment by ElmiraYazdani** [comment]
My problem has been solved 
Thank you for introducing dependencywalker.
