### ISSUE TITLE
VobjDesignPanel

### ISSUE THREAD

**Issue by ElmiraYazdani** [leoliuf/MRiLab#23]
Dear Dr. Liu
I have a question about VobjDesignPanel. I want to make a brain phantom with a tumor inside, but I need to have diffusion property. Is it possible to add it, if yes, may I ask you to guide me?
Thanks

**Comment by leoliuf** [comment]
Unfortunately, the current software doesn't support diffusion model explicitly. We are currently working to incorporate more complex tissue models but it will take some time to release. :)

**Comment by ElmiraYazdani** [comment]
Thank you very much
