### ISSUE TITLE
Error maximum gradient amplitude follow-up

### ISSUE THREAD

**Issue by IgnacioGit404** [leoliuf/MRiLab#24]
Thanks for the previous reply.

I can get the simulation to work with the following parameters:
ResFreq=ResPhase=60
FOVPhase=FOVFreq=20e-2
SliceThick = 8.5e-3
TE = 11e-3
DP_TR = TR = 22.5e-3
B0 = 0.0065T

And all other parameters set to the FIESTA defaults. These are the parameters in the paper I am trying to replicate (Low-Cost High-Performance MRI published 2015 by Mathieu Sarracanie et al).

However, in this paper the MaxSlewRate, MaxGrad and bandwith are different to the defaults, being 
MaxSlewRate = 0.7 mT/m/ms = 0.7T/m/s (MRiLab default 200)
MaxGrad = 1e-3 T/m (MRiLab default 50e-3)
Bandwidth = 10e3 (MRiLab default 80e3)

The sequence diagrams are mostly unaffected by changes to MaxSlewRate and MaxGrad, though these changes from the defaults then produce errors when I want to simulate a scan. Changing the bandwidth causes serious overlap in the sequence, which I can then fix by changing the CV values to CV1 = 6e-3 and CV2 = 7e-3 which keep the sequence as 3D bSSFP I believe.  

Would you happen to have any ideas why the slew rates and max gradients are still causing errors with these other settings? The minimum values I seem to be able to reach are a MaxSlewRate of 35 T/m/s and MaxGrad of 4 mT/m.

**Comment by leoliuf** [comment]
Given the relative low-performance gradient system you configured, you might want to extend the default tRamp period (determines how long to reach the target gradient amplitude from zero) in the Gxyz gradient macros so the MaxSlewRate can be happy. You can also extend the length of Gxyz gradient macros to make MaxGrad happy. Make sure there is no overlap between waveforms before scanning.

**Comment by IgnacioGit404** [comment]
That's perfect thank you, tRamp was indeed too low. I appreciate all your help!
