### ISSUE TITLE
Banding Artifact

### ISSUE THREAD

**Issue by ElmiraYazdani** [leoliuf/MRiLab#25]
I have a question about banding artifact on PSD-FIESTA
When I Loaded Brain (Standard Resolution 108 × 90 × 90) and Mag GaussianHead, I got this image:
What are these parts around image that I am showing by red color? How can I remove it?
![band](https://user-images.githubusercontent.com/48117052/62681842-e1d96380-b9cf-11e9-8730-deb3502e9f6d.jpg)

**Comment by leoliuf** [comment]
It might arise from the transient steady-state signal. You might want to acquire more image slices to mitigate this artifact.

**Comment by ElmiraYazdani** [comment]
Thank you so much.
