### ISSUE TITLE
T1 Mapping

### ISSUE THREAD

**Issue by ElmiraYazdani** [leoliuf/MRiLab#28]
Hi,
I'm having troubles about T1 Mapping with Inversion Recovery of MriLab;
I set TR=15000,TE=50 and TI=[700-900-1100-1300-1500-1700-1900] and acquire 7 images to make a t1 map
But there is a problem: with these TIs, the intensity of WM and GM (in brain tissues Phantom) are increasing but the CSF intensity is constant.
After TI around 3000 the CSF Intensity is increasing and WM and GM intensities are constant. What is the problem? Is it possible to do t1 mapping with MRi-Lab?

**Comment by leoliuf** [comment]
Hi @elmirayazdani ,
I tried the simulation with TI=[700-1700], I can see the different signal from CSF, GM, and WS from the simulated images. Please see below images (Left: TI=700; Right TI=1700). Could you please give a better description of your observations and maybe some images might be helpful for diagnosis. Thanks.

![image](https://user-images.githubusercontent.com/6468385/63813761-1f0c8380-c8f4-11e9-8ee1-4616e8791767.png)

**Comment by ElmiraYazdani** [comment]
Thank you for your response
I cannot see such results like yours
First I applied IR sequence with these settings:
![IR](https://user-images.githubusercontent.com/48117052/63831625-4317a580-c984-11e9-810e-2e96e31bd976.jpg)

for TI 700 and 1700 I got these images:
![1](https://user-images.githubusercontent.com/48117052/63831270-8de4ed80-c983-11e9-85f2-867d68a443d5.jpg)
![2](https://user-images.githubusercontent.com/48117052/63831281-950bfb80-c983-11e9-8509-799b831f2421.jpg)
Then I tried IR-SE with these settings:
![SE](https://user-images.githubusercontent.com/48117052/63831352-ba990500-c983-11e9-8e9e-bad785bde11c.jpg)
And I got these images for TI=700 and 1700:
![1SE](https://user-images.githubusercontent.com/48117052/63831418-da302d80-c983-11e9-9237-62ec5816c06e.jpg)
![2SE](https://user-images.githubusercontent.com/48117052/63831442-e87e4980-c983-11e9-90d5-fd88866b0e51.jpg)
And I can see one line in CSF part, what is the problem with it?
![2SE](https://user-images.githubusercontent.com/48117052/63831563-1e233280-c984-11e9-98bb-cab5563ebf4d.jpg)
Thank you in advance

**Comment by ElmiraYazdani** [comment]
and, May I ask you to tell me what is the setting for your results?

**Comment by leoliuf** [comment]
You may want to display the image side-by-side (like my example) to appreciate the contrast difference from scans. Notice that the image preview is not scaled the same for different scans. You can use MatrixUser and follow the steps in Chapter 6.2 of the user manual.

**Comment by ElmiraYazdani** [comment]
Here I have done what you asked me, in below image (Left: TI=400, Middle: TI=700; Right TI=1700).
I expected that all tissues have a same behavior, but as you can see the intensity of CSF is decreasing, just one of the WM/GM tissues have a good behavior (increasing their intensities by increasing TI)
![12](https://user-images.githubusercontent.com/48117052/64059516-71d78b00-cbd3-11e9-9fab-ef0b258feb70.jpg)
Even for two other values in below image (left: TI=2400, Right: TI=3200) you can see the incorrect behavior of two tissues:
![14](https://user-images.githubusercontent.com/48117052/64059680-908b5100-cbd6-11e9-8ea9-1994cb1e8dcf.jpg)
And here is my setting:
![15](https://user-images.githubusercontent.com/48117052/64059707-f081f780-cbd6-11e9-80e9-7b13b3838903.jpg)
May I ask you to provide me the screenshot of your setting, actually I just changed TI parameter and the other parameters are as default.

**Comment by DreymaR** [comment]
I don't see what's wrong here. For (400,700,1400) ms TI I got a CSF signal of (-0.8,-0.7,-0.4) relative to M0, in an independent MatLab IR simulation, for the given TR and a 3D readout. So yes, the magnitude of the CSF signal should be steadily decreasing with increasing TI in this range, as the signal is still inverted. The other tissues with their shorter T1 are increasing once they've crossed the axis. Or did I misunderstand something here?

**Comment by leoliuf** [comment]
Thanks for your explanation @DreymaR . The signal behavior is different before and after the crossing time point which is dependent on the T1 properties of each tissue.

**Comment by ElmiraYazdani** [comment]
Thanks
