### ISSUE TITLE
Frequency Encoding

### ISSUE THREAD

**Issue by ElmiraYazdani** [leoliuf/MRiLab#29]
Hi, I have a problem with frequency encoding
According to the below image in VCtl. TE when we set TE,  the frequency encoding (tMiddle) should be equal to VCtl.TE, here TE is 8ms but tMiddle in frequency direction is somewhere around 9. Actually, I did not change anything here, it is your default. If I change TE to every other value, the tMiddle will change to a number near VCtl.TE+1 or +2. 
How can I fix this problem?
![1](https://user-images.githubusercontent.com/48117052/64072777-f563ab80-cca9-11e9-890d-2ff5498f30a9.jpg)

**Comment by leoliuf** [comment]
TE is calculated with regards to the position of the excitation RF pulse. Notice that the RF pulse in your cases starts from ~1ms.

**Comment by ElmiraYazdani** [comment]
Thanks
