### ISSUE TITLE
PSD_FIESTA3D

### ISSUE THREAD

**Issue by romainVala** [leoliuf/MRiLab#3]
Hello

I was interested to simulate the banding artefact for different phase cycling of th bSSFp sequence.
So I play a little bit with the phase increment (CV3) 
I first test on the GM/WM/CSF phantome, with one uniform coil, uniform B0.
with the default phase (2*pi/2) the image looks ok, but when I put a RF phase increment (CV3 = 0) I get a big aliasing (in the phase encoding direction) only for the csf compartment.
I do not expect such an artifact ...
Any idea where it may come from ?

Many thanks

Romain

**Comment by leoliuf** [comment]
Can you provide the screenshot to help diagnosis? When you mentioned one uniform coil and uniform B0, did you mean you used additional coil and mag for the simulation?

**Comment by romainVala** [comment]
Hello,

thanks for your prompt reply, I did not find how to put a screen shot in 
the web interface

So I did not select any coil neither B0, so it takes the default.

I only select the GM/WM/CSF phantome and the PSD_FIESTA3D sequence, with 
the CV3 at pi I get the first attached figure but with the CV3 = 0 I get 
the warping (only for CSF) (second attach file)

Many thanks


Romain

**Comment by leoliuf** [comment]
Try to use smaller FlipAng and larger DP_Num (more dummy TR section). The artifact is caused by the transient steady-state signal from CSF. You can use SpinWatcher to check MR signal from individual voxel.

**Comment by romainVala** [comment]
ok, I will have a look, but I do not understand why his is dependent of 
the RF phase.

**Comment by romainVala** [comment]
Hi
I notice a bug when I put a DP_Num greater than 700 (for 8 slices)
it stop ate TR Counts = 640 or 700  (number of TR without dummy scan) and complains about wrong dimension. 
Strange because it works ok for smaller DP_NUM

Thanks

Romain

**Comment by leoliuf** [comment]
Yes, I noticed that too. I will possibly change the limitation of DP_Num to any number in the future version. So far, the DP_Num must be smaller than total phase encoding steps.
