### ISSUE TITLE
T1 and T2 for varying B0s

### ISSUE THREAD

**Issue by IgnacioGit404** [leoliuf/MRiLab#31]
Hi,

I've been doing simulations with very low and high field strengths and was wondering whether T1 and T2 values of the phantom were adjusted automatically in MRiLab as the field strength changes following some formula, or whether they remained the same?  

I ask as in the latter case I would have to adjust the T1s and T2s for the various field strengths I am using.

Many thanks.

**Comment by leoliuf** [comment]
The properties of the digital phantom are fixed and need to be modified accordingly.

**Comment by IgnacioGit404** [comment]
Thank you for the prompt response! I will take this into account.
