### ISSUE TITLE
Interslice Gap

### ISSUE THREAD

**Issue by elliot-fox** [leoliuf/MRiLab#32]
Hi,

I'm doing Fast Spin Echo 3-D acquisitions and was wondering if there is any way I can fix an interslice gap? I didn't see anything about it in the user guide although I might have missed it.

Many Thanks.

**Comment by leoliuf** [comment]
Do you mean 2D-FSE with selective RF for a thin slice?

**Comment by elliot-fox** [comment]
Yes I do mean that, at the moment I'm having to manually set the field of views for each slice (of 14), is there a way I can automate the slice positions in the code to get 14 2D slices across the brain ?

**Comment by leoliuf** [comment]
You can also use Cartesian encoding in the slice direction to get multiple slices just like the default 3D mode. I am currently implementing 2D mode but unfortunately, it is not available in the current MRiLab version.

**Comment by elliot-fox** [comment]
Ok thank-you, also is there any information on how to use batch sim, I don't think the user guide says anything about it?

**Comment by leoliuf** [comment]
Please see the user guide section 4.1 Running Simulation. The last paragraph talked about the batch simulation. Also please see my answer to #30

**Comment by elliot-fox** [comment]
Ok thank-you for your help
