### ISSUE TITLE
FSE streak artifact

### ISSUE THREAD

**Issue by IgnacioGit404** [leoliuf/MRiLab#33]
Hi,

I've been having difficulties simulating an FSE sequence with images coming out looking very 'streaky' e.g. below. They seem to maintain only the high frequency information.

![Steaky](https://user-images.githubusercontent.com/51709212/66326150-67ba5200-e920-11e9-9718-f793f588f5ec.png)

I was wondering what this might be due to? My current parameters are:
ResFreqxResPhase: 448 x 290
FOVFreqxFOVPhase: 23x20 cm
FlipAng: 90
TE: 96ms
TR: 5420ms
B0: 1.5T

FSE_ShotNum: 29
FSE_ETL: 10
FSE_ESP: 10e-3

CV1: 1e-3
CV2: 3e-3

**Comment by leoliuf** [comment]
Your simulated image resolution must be equal to or lower than the phantom in-plane resolution in order to avoid this artifact due to digitization.

**Comment by IgnacioGit404** [comment]
I was desperately trying to think of a physical reason why this might happen and completely overlooked that digitization might be a cause! 

Many thanks
