### ISSUE TITLE
Using a bespoke phantom object

### ISSUE THREAD

**Issue by IgnacioGit404** [leoliuf/MRiLab#34]
Hi,

I've been trying to get MRiLab to work with a bespoke phantom brain, in the VObj format as for the other brain phantoms, except my dimensions are 120x77x120. The brain loads into MRiLab fine, and the previews also appear fine, but any attempt at using the object for  simulation results in a falied reconstruction which is essentially just noise, for any sequence selected. 
I tried to upload the file here bad sadly the .mat format is not supported. 

Many thanks,
Ignacio

**Comment by leoliuf** [comment]
Hi Ignacio,
Did you try the default phantom and see the same result of just noise? Did you also ensure that you provide all required relaxation properties including T1, T2, T2*, and PD for the phantom? It can be challenging to diagnose without knowing more information about your experimental setup.

Fang

**Comment by IgnacioGit404** [comment]
Hi Fang,
Thanks for the reply. I have indeed tried several of the default phantom objects and they reconstruct fine, hence my confusion. I have sent a copy of the object file to the gmail address you provide as github sadly doesn't accept .mat file uploads. The object is a 120x77x120 phantom and I provide rho, T1, T2, T2*, ECon, Mass density, dimensions, resolution, gyro and chemshift. I have tried to replicate the VObj struct used for the other phantoms as closely as possible.
Thanks,
Ignacio

**Comment by leoliuf** [comment]
Hi Ignacio,
I have tried your phantom. You need to 1) change your Gyromagnetic ratio to the correct value; 2) exchange the XDim and YDim in VObj. You should be able to get this 

![image](https://user-images.githubusercontent.com/6468385/83224097-98b6f380-a14a-11ea-9cb8-30bc5db843d2.png)

Good luck with your project.

Fang
