### ISSUE TITLE
Question about "spin per voxel"

### ISSUE THREAD

**Issue by 777Beta** [leoliuf/MRiLab#36]
Hi,

I have a question about how multiple spins are distributed in a voxel. For example, the phantom to be simulated has in plane resolution of 1mm x 1mm, and I set 5 spins per voxel. Does this "voxel" refer to the phantom resolution or image resolution? How are these 5 spins (or any number larger than 1) physically located in this voxel?

Thank you!

**Comment by leoliuf** [comment]
The spins in voxel are primarily designed to simulate T2* effect. They don't have physical locations in each voxel in the subvoxel level. They, however, experience different B0 field variation to generate spin dephasing due to T2* effect.

**Comment by leoliuf** [comment]
![image](https://user-images.githubusercontent.com/6468385/96805730-4bc90780-13e0-11eb-8f9f-93d74d454e4c.png)

See more details in the paper
https://ieeexplore.ieee.org/document/7676360
