### ISSUE TITLE
SeqXMLFile error

### ISSUE THREAD

**Issue by tlemsl** [leoliuf/MRiLab#44]
Hi i work on matlab 2021b, MRILab-1.3 and I got SeqXMLFile error 

![error](https://user-images.githubusercontent.com/50408036/155347520-40a49e46-aef9-428e-8d6f-cb0401800806.PNG)

I don't know why this error is happening.  Can you give me some advice?

**Comment by leoliuf** [comment]
You need to choose and load a sequence first to run the simulation.
