### ISSUE TITLE
Issue with GPU

### ISSUE THREAD

**Issue by JTPlayzYT** [leoliuf/MRiLab#45]
I am having an issue using my GPU, it gives an error on start saying "Detecting local GPU Information failed! Unrecognized function or variable 'gpuDeviceCount'"

**Comment by leoliuf** [comment]
Likely, your Matlab version is not supporting the 'gpuDeviceCount' function.

**Comment by sgkim2** [comment]
From my understanding, it seems like the issue is with a missing toolbox rather than a version problem. Using the mathworks/matlab-deep-learning docker image may be helpful.
