### ISSUE TITLE
Phantom creation

### ISSUE THREAD

**Issue by deidieva** [leoliuf/MRiLab#46]
Hi, I would like to know how to create a phantom on your platform. I checked online and in the user guide but I am still stuck. I would like to create various phantoms such as spheres, cubes etc. I am rather a newbie in MatLab maybe that's why I couldn't make it

**Comment by leoliuf** [comment]
You might want to read this section https://leoliuf.github.io/MRiLab/manual/MRiLab_User_Guide_v1_3/MRiLab_User_Guidech5.html#x10-1010005.3

**Comment by deidieva** [comment]
thank you!
