### ISSUE TITLE
free induction decay  and other corresponding signals from a voxel

### ISSUE THREAD

**Issue by deidieva** [leoliuf/MRiLab#48]
Hi, I am having an issue finding out where to obtain the FID signal from? I can only see how to construct a sequence but not the output. I created a sequence with only 90 deg RF pulse. I saw there is "series" mat data in output files but I cannot find the FID signal. I have tried plotting VSig.Sx but it just looks like noise.

**Comment by leoliuf** [comment]
You can look at both 
VSig.Sx : A array storing x (real) component of acquired MR signal
VSig.Sy : A array storing y (imaginary) component of acquired MR signal

**Comment by deidieva** [comment]
thanks!
