### ISSUE TITLE
Manual Shimming - Very Simple Bug

### ISSUE THREAD

**Issue by ebiyik** [leoliuf/MRiLab#5]
Hello,

Thank you for the tool, it has been quite useful for me so far.

One issue is: Although the shimming tab is loaded, when I set shimming to manual, the program gives the warning "Please load Shim tab. Manual Shimming was not performed!".

The 8th line of \Src\Main\DoManualShim.m should be **'Sh_X2_Y2'** instead of 'X2_Y2'. I did not want to create a pull request for such a simple mistake :)

Have a nice day!

**Comment by leoliuf** [comment]
Thanks for picking up this.
